query GetCompanies_Query($pagination: PaginationInput) {
  getCompanies(pagination: $pagination) {
    ...FullCompanyInfo
  }
}
mutation UpsertCompan_yMutation($input: CompanyUpsertInput!) {
  upsertCompany(input: $input) {
    ...FullCompanyInfo
  }
}

subscription Company_Updated {
  companyUpdated {
    id
    name
    timestamp
  }
}

fragment FullCompanyInfo on CompanyOutput {
  id
  name
}
