query GetCompaniesQuery {
  getCompanies {
    ...FullCompanyInfo
  }
}
mutation UpsertCompanyMutation($input: CompanyUpsertInput!) {
  upsertCompany(input: $input) {
    ...FullCompanyInfo
  }
}

fragment FullCompanyInfo on CompanyOutput {
  id
  name
}
