query GetCompaniesQuery($pagination: PaginationInput) {
  getCompanies(pagination: $pagination) {
    ...FullCompanyInfo
  }
}
mutation UpsertCompanyMutation($input: CompanyUpsertInput!) {
  upsertCompany(input: $input) {
    ...FullCompanyInfo
  }
}

subscription CompanyUpdated {
  companyUpdated {
    id
    name
    timestamp
  }
}

fragment FullCompanyInfo on CompanyOutput {
  id
  name
}
